version: '3.8'
services:
  backend:
    #image: sakoes/cpter:latest
    #container_name: cpter_backend_prod
    build: 
      context: .
      dockerfile: Dockerfile.prod
    #command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 80 --reload'
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - DB_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    #env_file:
        #- ./.env  
    depends_on:
      - db
      
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data_prod:
