# https://medium.com/analytics-vidhya/how-to-understand-building-images-with-docker-compose-24cbdbc0641f

version: '3'
services:
  backend:
    image: sakoes/cpter:latest
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 80'
    #command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik

volumes:
  postgres_data:
